language: python
sudo: false
python: 3.7

git:
  depth: 2

branches:
  only:
    - master
    - devel
    - /^[0-9]+\.[0-9]+\.[0-9]+[.0-9ab]*$/

env:
  global:
    - GITHUB_REPO=Midnighter/travis-release-notes

matrix:
  fast_finish: true

install:
  - pip install pytest hypothesis

script:
  - pytest

