language: python
sudo: false
python: 3.7

git:
  depth: 2

branches:
  only:
    - master
    - devel
    - /^[0-9]+\.[0-9]+\.[0-9]+[.0-9ab]*$/

env:
  global:
    - GITHUB_REPO=Midnighter/travis-release-notes

matrix:
  fast_finish: true

install:
  - pip install pytest hypothesis

script:
  - pytest

stages:
  - test
  - name: deploy
    if: tag IS present

jobs:
  include:
    - stage: deploy
      install: skip
      script: skip
      deploy:
        - provider: releases
          edge: true
          skip_cleanup: true
          api_key: $GITHUB_TOKEN
          release_notes_file: "release-notes/${TRAVIS_TAG}.md"
          on:
            tags: true
            repo: $GITHUB_REPO
