language: python
sudo: false
python: 3.7

git:
  depth: 2

branches:
  only:
  - master
  - devel
  - /^[0-9]+\.[0-9]+\.[0-9]+[.0-9ab]*$/

env:
  global:
  - GITHUB_REPO=Midnighter/travis-release-notes

stages:
- test
- name: deploy
  if: tag IS present

jobs:
  fast_finish: true
  include:
  - stage: test
    install:
    - pip install pytest hypothesis
    script:
    - pytest
  - stage: deploy
    install: skip
    script: skip
    deploy:
    - provider: releases
      skip_cleanup: true
      api_key: $GITHUB_TOKEN
      on:
        tags: true
        repo: $GITHUB_REPO

notifications:
  email: false
